version: '2'
services:
  postgres:
    image: postgres:13.4
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./.postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - 6379:6379

