"""empty message

Revision ID: 23af7842dce
Revises: 1331b8a6a07
Create Date: 2015-05-24 13:33:04.405958

"""

# revision identifiers, used by Alembic.
revision = '23af7842dce'
down_revision = '1331b8a6a07'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('youtube_url', sa.String(), nullable=True))
    op.drop_column('results', 'result_all')
    op.drop_column('results', 'result_no_stop_words')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('result_no_stop_words', postgresql.JSON(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('result_all', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('results', 'youtube_url')
    ### end Alembic commands ###
